# Generated by Django 4.2.4 on 2023-09-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("likes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likeditem",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
