# Generated by Django 4.2.4 on 2023-09-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="unit_price",
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="null"),
            preserve_default=False,
        ),
    ]
