# Generated by Django 4.2.4 on 2023-09-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_price_product_unit_price_product_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="name",
            new_name="title",
        ),
    ]
